/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnative_io_EPoll */

#ifndef _Included_jnative_io_EPoll
#define _Included_jnative_io_EPoll
#ifdef __cplusplus
extern "C" {
#endif
#undef jnative_io_EPoll_EPOLLIN
#define jnative_io_EPoll_EPOLLIN 1L
#undef jnative_io_EPoll_EPOLLOUT
#define jnative_io_EPoll_EPOLLOUT 2L
#undef jnative_io_EPoll_EPOLLACCEPT
#define jnative_io_EPoll_EPOLLACCEPT 4L
#undef jnative_io_EPoll_EPOLLRDHUP
#define jnative_io_EPoll_EPOLLRDHUP 8L
#undef jnative_io_EPoll_EPOLL_CTL_ADD
#define jnative_io_EPoll_EPOLL_CTL_ADD 1L
#undef jnative_io_EPoll_EPOLL_CTL_DEL
#define jnative_io_EPoll_EPOLL_CTL_DEL 2L
#undef jnative_io_EPoll_EPOLL_CTL_MOD
#define jnative_io_EPoll_EPOLL_CTL_MOD 3L
#undef jnative_io_EPoll_EPOLLONESHOT
#define jnative_io_EPoll_EPOLLONESHOT 1073741824L
/*
 * Class:     jnative_io_EPoll
 * Method:    eventSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnative_io_EPoll_eventSize
  (JNIEnv *, jclass);

/*
 * Class:     jnative_io_EPoll
 * Method:    eventsOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnative_io_EPoll_eventsOffset
  (JNIEnv *, jclass);

/*
 * Class:     jnative_io_EPoll
 * Method:    dataOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnative_io_EPoll_dataOffset
  (JNIEnv *, jclass);

/*
 * Class:     jnative_io_EPoll
 * Method:    eventFd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnative_io_EPoll_eventFd
  (JNIEnv *, jclass);

/*
 * Class:     jnative_io_EPoll
 * Method:    epollCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnative_io_EPoll_epollCreate
  (JNIEnv *, jclass);

/*
 * Class:     jnative_io_EPoll
 * Method:    epollCtl
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_jnative_io_EPoll_epollCtl
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     jnative_io_EPoll
 * Method:    epollWait
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_jnative_io_EPoll_epollWait
  (JNIEnv *, jclass, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
