/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnative_io_AIO */

#ifndef _Included_jnative_io_AIO
#define _Included_jnative_io_AIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnative_io_AIO
 * Method:    setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnative_io_AIO_setup
  (JNIEnv *, jclass);

/*
 * Class:     jnative_io_AIO
 * Method:    setEventFd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jnative_io_AIO_setEventFd
  (JNIEnv *, jclass, jint);

/*
 * Class:     jnative_io_AIO
 * Method:    submitIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnative_io_AIO_submitIO
  (JNIEnv *, jclass);

/*
 * Class:     jnative_io_AIO
 * Method:    preparePRead
 * Signature: (JILjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_jnative_io_AIO_preparePRead
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jint);

/*
 * Class:     jnative_io_AIO
 * Method:    preparePWrite
 * Signature: (JILjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_jnative_io_AIO_preparePWrite
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jint);

/*
 * Class:     jnative_io_AIO
 * Method:    getEvents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnative_io_AIO_getEvents
  (JNIEnv *, jclass);

/*
 * Class:     jnative_io_AIO
 * Method:    destory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnative_io_AIO_destory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
